spring.application.name=ox_quiz
spring.output.ansi.enabled=always

#MySQL 연결
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/quiz_db

# 환경설정 파일에서 환경변수를 만드는 법
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PW:1111}

# SQL 로그
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
### 테이블 자동 생성 전략
# create : 완전개발 초기
# update : 개발 초기/중기
# validate : DB 안정화
# none :  배포
spring.jpa.hibernate.ddl-auto=create

# SQL 바인딩 파라미터 로그
logging.level.org.hibernate.orm.jdbc.bind=trace

# 방언설정
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Spring Security 기본 계정 비활성화용(선택)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration